### ISSUE TITLE
[feature]: Bulk editing

### ISSUE THREAD

**Issue by patrickblackjr** [makeplane/plane#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a user, I should be able to select multiple issues and perform bulk actions, such as adding labels, assignees, or modules.

### Why should this be worked on?

This is particularly helpful during onboarding to help get issues into their appropriate state where minor modifications could be made, but this would be useful frequently, combined with issue search. For instance, if you have noticed you have been getting a lot of issues about Docker, and you decide to create a new Docker label. Now you want to apply in in bulk to existing Docker issues for reporting and searchability.

**Comment by vihar** [comment]
Hey @patrickblackjr, this is a great feature request, we plan to take this up for our new Spreadsheet view.

**Comment by bahodge** [comment]
Hi, I'm new to plane so sorry if I miss anything you are already working on. I'm glad you are working on this feature but I would like to also request some considerations.

I mostly only care about mass editing issues because that is my "unit of work".

- **apply labels to many issues**
- **change state**
- **assign/unassign**. this is useful for onboarding/offboarding people
- **add/remove issues from modules**. this looks like it kind of exists by going to `<project> > modules > module > kanban/list layout > add existing issue` but it is somewhat difficult to navigate.
- **add/remove issues from cycles**

**Comment by vihar** [comment]
@bahodge, these suggestions are great. curious, what are you using plane for? maybe if you could explain your use case, it'll help us come up with a better user experience

**Comment by bahodge** [comment]
Main use case is for software development on a small team of developers. I'm just a total noob to plane so please take my suggestions with a grain (or bucket) of salt.

For me:
Modules -> projects, initiatives, epics or user stories
Cycles -> sprints/iterations/timelines with deliverables
Issues -> units of work to be done to call a module/cycle complete

Here are a few use cases that I think I would come across pretty often

## Situation 1

If I had a backlog of issues, I would want to be able to label a bunch of them as "tech debt" at once. I would then want to be able to filter for those issues based on the label (exists) but then attach those issues to a cycle so that we can say, by the end of this cycle, we want all these issues closed.

## Situation 2

I created a module A with a bunch of issues, but now the scope of the module A has expanded. I create another module B and take some of the issues from module A and attach them to module B.

## Situation 3

Team member A is burnt out on UI work, I would want to be able to unassign team member A from those issues and assign them to backend issues.

## Situation 4

Project is canceled and now I need to close all the issues in module A.

Also, thank you.

**Comment by Huuuze** [comment]
I'll second @bahodge's comments and scenarios. The lack of a bulk edit feature will cause devs to waste time making individual edits to dozens/hundreds of issues in Plane.

**Comment by vihar** [comment]
Coming really soon. Thanks for sharing the use-cases, @bahodge.

![CleanShot 2024-01-03 at 02 08 59@2x](https://github.com/makeplane/plane/assets/16307796/3b4e3bf5-b3c8-4515-a1d7-dc9075245a78)

**Comment by niltonvasques** [comment]
This is also useful when the Cycle finishes and leftovers needs to be moved forward to the next cycle.

**Comment by carbogninalberto** [comment]
@vihar this is great, do you have a release date/version for this feature? I am planning to move from linear to plane

**Comment by sabgaby** [comment]
Second this! When will this be available? It's one of my main headaches

**Comment by gchanchal** [comment]
Bulk Edit - Folks, thanks for reaching out and he share your pain. The feature is WIP and we are planning tentatively in May 2024. Will keep you posted on the progress

**Comment by vihar** [comment]
Bulk editing is now live on our [One](https://plane.so/one) and Pro plans.

**Comment by sarahhenkens** [comment]
@vihar? Any plans to make this available in the free plan. This is an absolute basic feature of any project management tool to do bulk actions like assignee and labeling. It kinda boggled my mind this is a feature locked behind a paywall

**Comment by mredodos** [comment]
> [@vihar](https://github.com/vihar) Any plans to make this available in the free plan. This is an absolute basic feature of any project management tool to do bulk actions like assignee and labeling. It kinda boggled my mind this is a feature locked behind a paywall

agree we need on the free versions pls

**Comment by paulovbettio** [comment]
Any updates on it becoming a community feature? It being a paywalled feature is very odd and really surprised me when I discovered that.
