### ISSUE TITLE
[bug]: Open core instead of open source?

### ISSUE THREAD

**Issue by bevel-zgates** [makeplane/plane#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

To be able to integrate with external services:
![image](https://github.com/makeplane/plane/assets/78045045/81af755d-52cb-4873-a7b0-3190882c870f)

### Steps to reproduce

![image](https://github.com/makeplane/plane/assets/78045045/d5c321e5-1fad-4a8d-8d67-a34965336795)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by bevel-zgates** [comment]
Looks like there are some aspects of the service that are cloud-only. Can you provide a feature list of the components that are disabled for local deployments?

**Comment by AprilNEA** [comment]
I'm highly anticipating Github Sync, which will be my main reason for choosing Plane, and I hope it will be open-sourced soon.

**Comment by vihar** [comment]
Hello, everyone! This is Vihar. I'm one of the maintainers here at Plane. We are currently in the early stages of development, which is why we haven't open-sourced any integrations yet. Our goal is to first create an architecture that is easy to understand and contribute to. By doing so, the community will be able to benefit from creating their own integrations in the most effective manner possible. Rest assured, integrations will be made available for free and open-sourced in the near future. We appreciate your patience.

**Comment by bevel-zgates** [comment]
To bump @vihar I didn't read the material carefully it does look like you call this out specifically in your features brief:
![image](https://github.com/makeplane/plane/assets/78045045/152d1378-44f6-48de-bb63-0cbf9a9a4941)

I'll close for now. Thanks to your team @vihar excited to see where you go.

**Comment by Lermatroid** [comment]
Wanted to reopen this to ask if there are any updates. Almost a year later, and as far as I can tell it is still closed source? Just wanted to check. Thanks!

**Comment by vihar** [comment]
@Lermatroid, we are still figuring out the best way to open our integrations. What we had done so far had some missing pieces, and we are rebuilding it from scratch with a better stack. We will update once we are close to open-sourcing our SDKs. Hope this answers your questions. Given our roadmap, this should be out in Q2 2024.

**Comment by Lermatroid** [comment]
Awesome, thanks for the update @vihar!
