### ISSUE TITLE
[bug]: No obvious SSL certificate support

### ISSUE THREAD

**Issue by gareth-johnstone** [makeplane/plane#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I visit the URL i have plane.so self hosted on and there is no SSL support.

### Steps to reproduce

Go to website
no SSL

### Browser

Google Chrome

### Version

Self-hosted

**Comment by me-abhishekpal** [comment]
Hi @gareth-johnstone 

On the self-hosted version, you are running it via the nginx reverse proxy.
On nginx, you can setup a certbot which can generate the cert for you and you can replace all the http to https or configure the nginx to redirect http:// to https://

Give it a try !

**Comment by georg-schwarz** [comment]
As we had the same issue and spent quite some time on it, we`d like to share our setup:
- There is a **reverse proxy** serving at ports 80 (for certificate issuing) and 443 with SSL
- There is a **certbot** to issue the SSL certificate
- There is **plane** running on port 12345 - should be around version [v0.8-dev](https://github.com/makeplane/plane/releases/tag/v0.8-dev). Since the project seems to be in its early stages, things might have changed when you read this!

## 1. Setup Host Machine
 
1. Install Docker: https://docs.docker.com/engine/install/ubuntu/
2. Enable rootless Docker: https://docs.docker.com/engine/security/rootless/
3. Enable privileged ports for serving on 80 / 443: https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports

In our setup, we organized the following directories:
- `~/plane`: The plane files and configurations
- `~/volume/certbot`: The certbot volumes (logs, configs)
- `~/volume/nginx`: The nginx volumes (logs, configs)


## 2. Setup Plane.so
1. Follow self-host tutorial: https://docs.plane.so/self-hosting
2. In the version we used, you have to make some further configurations (overwrite passwords, add email settings)
3. Apply the configuration: `set -a; source .env; set +a;`
4. Start plane.so: `docker compose -f docker-compose-hub.yml up -d`

Make sure you configure the following variables to your needs in `.env`:
```
NGINX_PORT=12345
NEXT_PUBLIC_API_BASE_URL=https://<domain>.com
WEB_URL=https://<domain>.com
```
Please note the http**s** in the URLs.


## 3. Reverse Proxy


1. Setup SSL with certbot and nginx. I'll skip the necessary steps to issue the certificate. We found this tutorial helpful: https://mindsers.blog/post/https-using-nginx-certbot-docker/
2. Start the reverse proxy: `docker compose up webserver -d`

These are the final configurations we used:

File `volume/nginx/conf/default.conf`:
```
server {
    listen 80;
    listen [::]:80;

    server_name <domain>.com www.<domain>.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://<domain>.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name <domain>.com www<domain>.com;

    ssl_certificate /etc/nginx/ssl/live/<domain>.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/<domain>.com/privkey.pem;
    
    location / {
	proxy_pass http://<domain>.com:12345;
	proxy_set_header  X-Real-IP  $remote_addr;
	proxy_set_header  Host $host;
	proxy_set_header X-Forwarded-Proto $scheme;
	add_header 'Content-Security-Policy' 'upgrade-insecure-requests'; # Otherwise error:  The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'.
    }
}
```

File `docker-compose.yaml`
```
version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./volume/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./volume/certbot/www:/var/www/certbot/:ro
      - ./volume/certbot/conf/:/etc/nginx/ssl/:ro
      - ./volume/nginx/log/:/var/log/nginx/:rw
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/letsencrypt/:rw
```

## Caveats

- The port of plane needs to be exposed as well (I think)
- I'm unsure about the security implications of the added header `add_header 'Content-Security-Policy' 'upgrade-insecure-requests';` in the reverse-proxy

Let me know if you have thoughts (especially on how to deal with the caveats)!

**Comment by mohaa7** [comment]
> File `docker-compose.yaml`
> 
> ```
> version: '3'
> 
> services:
>   webserver:
>     image: nginx:latest
>     ports:
>       - 80:80
>       - 443:443
>     ...
> ```

@georg-schwarz, Do you mean adding that config under `services` in ~/plane/docker-compose.yaml?

> ```
>   certbot:
>     image: certbot/certbot:latest
>     volumes:
>       - ./volume/certbot/www/:/var/www/certbot/:rw
>       - ./volume/certbot/conf/:/etc/letsencrypt/:rw
> ```

As you have created the ~/volume/ directory, shouldn't those paths be like the lines below, started with `..`?
```bash
       - ../volume/certbot/www/:/var/www/certbot/:rw
       - ../volume/certbot/conf/:/etc/letsencrypt/:rw
```
Since `.` points to ~/plane/ where the file docker-compose.yaml is located and we launch the plane from there!



> Make sure you configure the following variables to your needs in `.env`:
> 
> ```
> NGINX_PORT=12345
> NEXT_PUBLIC_API_BASE_URL=https://<domain>.com
> WEB_URL=https://<domain>.com
> ```

Why 12345, why not 443? as we are going to have HTTPS!
What does `NEXT_PUBLIC_API_BASE_URL` do?

**Comment by georg-schwarz** [comment]
> @georg-schwarz, Do you mean adding that config under `services` in ~/plane/docker-compose.yaml?

No. I created a separate `~/docker-compose.yaml` file. So with the plane one there are 2 in total. This way, you can easily upgrade plane independently of the reverse proxy adding SSL.

> Why 12345, why not 443? as we are going to have HTTPS!

Since that port will be exposed by the reverse proxy, not plane itself. 

> What does `NEXT_PUBLIC_API_BASE_URL` do?

I don't know tbh, I'm also just another plane user ;-)

**Comment by mohaa7** [comment]
Thank you for your reply.

```
$ docker compose -f ~/docker-compose.yml up -d
[+] Running 3/3
 ✔ Network gmohaa_default        Created                                                                                                          0.1s 
 ✔ Container mohaa-certbot-1    Started                                                                                                          0.2s 
 ✔ Container mohaa-webserver-1  Started
```

Looking at `./volume/nginx/log/error.log`, there's this issue:
```
2023/10/15 10:30:19 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/live/plane.example.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/ssl/live/plane.example.com/fullchain.pem, r) error:10000080:BIO routines::no such file)

```
What does it mean?

---

> I created a separate `~/docker-compose.yaml` file

It should be run before the plane deocker-compose file, right? If I run yours after the plane's yaml file, I  get the error "_port 80 is already allocated_" in the last line of the following snippet:

```
$ docker compose -f ~/plane/docker-compose-hub.yml up -d
[+] Running 10/10
 ✔ Container plane-redis            Started                                                                                                      0.0s 
 ✔ Container plane-db               Started                                                                                                      0.0s 
 ✔ Container plane-minio            Started                                                                                                      0.0s 
 ✔ Container api                    Started                                                                                                      0.0s 
 ✔ Container plane-createbuckets-1  Started                                                                                                      0.0s 
 ✔ Container beatworker             Started                                                                                                      0.0s 
 ✔ Container bgworker               Started                                                                                                      0.0s 
 ✔ Container web                    Started                                                                                                      0.0s 
 ✔ Container space                  Started                                                                                                      0.0s 
 ✔ Container proxy                  Started                                                                                                      0.0s 

$ docker compose -f ~/docker-compose.yml up -d
[+] Running 1/2
 ✔ Container mohaa-certbot-1    Started                                                                                                          0.0s 
 ⠼ Container mohaa-webserver-1  Starting                                                                                                         0.5s 
Error response from daemon: driver failed programming external connectivity on endpoint mohaa-webserver-1 (27c5484e1df0f48f6680018dfbd34d411dc52dc74e1246558be91362f7f1103d): Bind for 0.0.0.0:80 failed: port is already allocated
```
`ss -tunlp | grep \:80`
```
tcp   LISTEN 0      4096         0.0.0.0:80        0.0.0.0:*    uid:1000 ino:213775 sk:7 cgroup:/user.slice/user-1000.slice/user@1000.service/app.slice/docker.service <->         
tcp   LISTEN 0      4096            [::]:80           [::]:*    uid:1000 ino:214368 sk:8 cgroup:/user.slice/user-1000.slice/user@1000.service/app.slice/docker.service v6only:1 <->
```

**Comment by mohaa7** [comment]
Thank you for your reply. I still have an issue getting `port 80 is already allocated` that is mentioned at the end of this comment.

If I run your yml file:

```
$ docker compose -f ~/docker-compose.yml up -d
[+] Running 3/3
 ✔ Network mohaa_default        Created                                                                                                          0.1s 
 ✔ Container mohaa-certbot-1    Started                                                                                                          0.2s 
 ✔ Container mohaa-webserver-1  Started
```

Both Nginx and Certbot containers are started, but looking at `./volume/nginx/log/error.log`, there was this issue:

```
2023/10/15 10:30:19 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/live/plane.example.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/ssl/live/plane.example.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
```

1. Doesn't it need a `certonly` command at the end of the **certbot** section in `docker-compose.yaml`?
2. Nginx and Certbot are dependent on each other:
    - Nginx is expected for the 'fullchain.pem' file, but failed as it still needs to be created by the Certbot!
    - Certbot expected for a running web server listening on 80, but failed as Nginx failed previously for the lack of a pem file!

to solve these issues, @georg-schwarz, I onverted sections in the compose file into these two separated files:
- docker-compose-certbot.yml
- docker-compose-nginx.yml

`~/docker-compose-certbot.yml` has these lines:

```
version: "3.8"

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email <your_email> --agree-tos --no-eff-email --force-renewal -d <your_domain>
```

Then I ran these commands:

```
mkdir -p ~/volume/certbot/www
cd ~/volume/certbot/www/
sudo python3 -m http.server 80 & #run a temporary HTTP server to let LetsEncrypt communicate with your domain
docker compose -f ~/docker-compose-certbot.yml up
find ~/volume/ -name fullchain.pem #to ensure the pem file has been saved there
sudo killall python3
```

Now the required _pem_ file for starting Nginx is generated and saved locally in `/volume/certbot/conf/live/<your_domain>` that will be mounted to /etc/nginx/ssl/ by running the other compose file:

`docker-compose-nginx.yml`:

``` 
version: "3.8"

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./volume/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./volume/certbot/www:/var/www/certbot/:ro
      - ./volume/certbot/conf/:/etc/nginx/ssl/:ro
      - ./volume/nginx/log/:/var/log/nginx/:rw
```

Run Nginx:
`docker compose -f ~/docker-compose-nginx.yml up -d`

Run Plane:
`docker compose -f ~/plane/docker-compose-hub.yml up -d`

---

Now, I got this error:

```
Error response from daemon: driver failed programming external connectivity on endpoint proxy (a090ewt67bhfdsa6dff194a38bfbh43kj3boigd80511885f961b8ba7be17bc41d1f): Bind for 0.0.0.0:80 failed: port is already allocated
```

The error message "_Bind for 0.0.0.0:80 failed: port is already allocated_" indicates that the port 80 on the host machine is already in use by another service. In this case, first-run compose file is already using port 80.

@georg-schwarz , What if I change the Nginx service to use port 8080 instead of 80? Here's how I did this:

```
services:
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
```

Is it ok?

**Comment by vladimirevstratov** [comment]
> As we had the same issue and spent quite some time on it, we`d like to share our setup:
> 
> * There is a **reverse proxy** serving at ports 80 (for certificate issuing) and 443 with SSL
> * There is a **certbot** to issue the SSL certificate
> * There is **plane** running on port 12345 - should be around version [v0.8-dev](https://github.com/makeplane/plane/releases/tag/v0.8-dev). Since the project seems to be in its early stages, things might have changed when you read this!
> 
> ## 1. Setup Host Machine
> 1. Install Docker: https://docs.docker.com/engine/install/ubuntu/
> 2. Enable rootless Docker: https://docs.docker.com/engine/security/rootless/
> 3. Enable privileged ports for serving on 80 / 443: https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports
> 
> In our setup, we organized the following directories:
> 
> * `~/plane`: The plane files and configurations
> * `~/volume/certbot`: The certbot volumes (logs, configs)
> * `~/volume/nginx`: The nginx volumes (logs, configs)
> 
> ## 2. Setup Plane.so
> 1. Follow self-host tutorial: https://docs.plane.so/self-hosting
> 2. In the version we used, you have to make some further configurations (overwrite passwords, add email settings)
> 3. Apply the configuration: `set -a; source .env; set +a;`
> 4. Start plane.so: `docker compose -f docker-compose-hub.yml up -d`
> 
> Make sure you configure the following variables to your needs in `.env`:
> 
> ```
> NGINX_PORT=12345
> NEXT_PUBLIC_API_BASE_URL=https://<domain>.com
> WEB_URL=https://<domain>.com
> ```
> 
> Please note the http**s** in the URLs.
> 
> ## 3. Reverse Proxy
> 1. Setup SSL with certbot and nginx. I'll skip the necessary steps to issue the certificate. We found this tutorial helpful: https://mindsers.blog/post/https-using-nginx-certbot-docker/
> 2. Start the reverse proxy: `docker compose up webserver -d`
> 
> These are the final configurations we used:
> 
> File `volume/nginx/conf/default.conf`:
> 
> ```
> server {
>     listen 80;
>     listen [::]:80;
> 
>     server_name <domain>.com www.<domain>.com;
>     server_tokens off;
> 
>     location /.well-known/acme-challenge/ {
>         root /var/www/certbot;
>     }
> 
>     location / {
>         return 301 https://<domain>.com$request_uri;
>     }
> }
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     http2 on;
> 
>     server_name <domain>.com www<domain>.com;
> 
>     ssl_certificate /etc/nginx/ssl/live/<domain>.com/fullchain.pem;
>     ssl_certificate_key /etc/nginx/ssl/live/<domain>.com/privkey.pem;
>     
>     location / {
> 	proxy_pass http://<domain>.com:12345;
> 	proxy_set_header  X-Real-IP  $remote_addr;
> 	proxy_set_header  Host $host;
> 	proxy_set_header X-Forwarded-Proto $scheme;
> 	add_header 'Content-Security-Policy' 'upgrade-insecure-requests'; # Otherwise error:  The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'.
>     }
> }
> ```
> 
> File `docker-compose.yaml`
> 
> ```
> version: '3'
> 
> services:
>   webserver:
>     image: nginx:latest
>     ports:
>       - 80:80
>       - 443:443
>     restart: always
>     volumes:
>       - ./volume/nginx/conf/:/etc/nginx/conf.d/:ro
>       - ./volume/certbot/www:/var/www/certbot/:ro
>       - ./volume/certbot/conf/:/etc/nginx/ssl/:ro
>       - ./volume/nginx/log/:/var/log/nginx/:rw
>   certbot:
>     image: certbot/certbot:latest
>     volumes:
>       - ./volume/certbot/www/:/var/www/certbot/:rw
>       - ./volume/certbot/conf/:/etc/letsencrypt/:rw
> ```
> 
> ## Caveats
> * The port of plane needs to be exposed as well (I think)
> 
> Let me know if you have thoughts (especially on how to deal with the caveats)!
> 
> @me-abhishekpal It would be awesome if the plane-internal nginx would also allow configuration via an environment variable pointing to the certificates. However, I understand if this might not be in line with your commercial Open Source strategy.

Thank you! Use it now also.
