### ISSUE TITLE
[bug]: No projects visible to another admin

### ISSUE THREAD

**Issue by me-abhishekpal** [makeplane/plane#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you elect another user as admin of a workspace, that user is not seeing the projects already created in the workspace until he/she is explicitely added to the project.

![image](https://github.com/makeplane/plane/assets/2958671/4b6453be-400b-4f97-85a8-a54c45d661e3)
Admin with specific project permission

It is confusing since the dashboard does not show any thing despite the project and issues in those projects.

![image](https://github.com/makeplane/plane/assets/2958671/49cbb202-a4a8-4cf7-aa09-a28ab4957068)
Admin without specific project permission

### Steps to reproduce

1. Login with an admin to a workspace.
2. Give workspace admin access to another user.
3. Login with another user
4. Check the Dashboard, Projects etc .assigned to you

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@me-abhishekpal, my apologies for the delayed response regarding this issue. 

This was intentional, as when projects are set to `secret`, the creators are required to invite administrators. You can find further details in our documentation at https://docs.plane.so/projects#key-project-attributes.

We are currently developing a solution to provide administrators with more information about secret projects. We will create a new issue and share our complete PRD (Product Requirements Document) shortly.

cc: @bhaveshraja, @sriramveeraghanta, @vamsi, @Shivangi-jain33
