### ISSUE TITLE
[bug]: Buttons have too much padding in mobile devices

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Buttons have too much padding and unable to scroll horizontally on mobile devices.

### Steps to reproduce

1. Go to your `Workplace`.
2. Go to your `Project` that you have created.
3. Under the `Project` page section is there, to to page section.

Like this `Workplace > Project > Pages`

![Buttons Padding](https://github.com/makeplane/plane/assets/97095857/2b8095aa-a8fe-4dea-8f45-c2881d485224)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by kblueberry** [comment]
@ChandanJal I would rather changed design of tabs on mobile devices, not only paddings, because even with smaller paddings with current design they look ackward.

My suggestions:
1) dropdown list with tabs on mobile screens
2) vertical list of tabs

What do you think about this? Is there ready UX mockups for this tab list on mobile screens or if not, whom can I speak about this?

**Comment by kblueberry** [comment]
This is fixed in scope of https://github.com/makeplane/plane/pull/1387
