### ISSUE TITLE
[bug]: Invitation redirects to sign in

### ISSUE THREAD

**Issue by pascal-klesse** [makeplane/plane#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If i click on the link in the invited email, i will redirect to login. This is really strange behavior. I am prompted to enter email and password but I have not set a password yet.

### Steps to reproduce

1. Login as admin
2. Invite new member to workspace
3. open email
4. click on link in emal
5. confirm invite
6. now you are on the login and the app asks for email and password

### Browser

Google Chrome

### Version

Self-hosted

**Comment by aaryan610** [comment]
Hi @pascal-klesse, in the sign-in form, there's also an option to `Sign Up` if you aren't already a user. You can click on that option to sign up.

**Comment by calbrecht** [comment]
https://github.com/makeplane/plane/issues/1290#issuecomment-1620418733

**Comment by tomdevelops** [comment]
I'm experiencing the same issue. When I click on 'Accept,' I am redirected to the Sign In Page instead of being prompted to enter a password to complete the invitation process. It would be more intuitive if a password dialog appeared after pressing 'Accept' to seamlessly finalize the invitation.

![image](https://github.com/makeplane/plane/assets/344384/82cabb14-e99d-4329-8930-30f402b8d8f6)
![image](https://github.com/makeplane/plane/assets/344384/e226afc8-c66e-4b91-a848-b582ad375713)

**Comment by HiceS** [comment]
There appears to currently not be an option to `Sign Up` even with the `ENABLE_SIGNUP="1"` and `ENABLE_EMAIL_PASSWORD="1"`

**Comment by HiceS** [comment]
A workaround exists where if you correctly setup your smtp server and get the verification emails you can still invite people they will just have to use magic link to sign in and you must enable `ENABLE_MAGIC_LINK_LOGIN="1"`

**Comment by vihar** [comment]
We have upgraded our onboarding experience, and the process should now be easier. For additional information, kindly consult our documentation at https://docs.plane.so/sign-up-sign-in.
