### ISSUE TITLE
[bug]: Insecure File Upload leads to XSS

### ISSUE THREAD

**Issue by l4rm4nd** [makeplane/plane#2004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I upload an SVG image file into a plane issue, I would assume that it is either blocked or the SVG content is sanitized before being uploaded and available to others.

However, uploading an SVG image file with XSS payload is allowed and not sanitized. Therefore, introducing a potential Stored Cross-Site Scripting (XSS) vulnerability.

This issue may be linked to https://github.com/makeplane/plane/issues/1988

### Steps to reproduce

1. Log into plane
2. Create an issue or select a pre-existing one
3. Upload an SVG image file with an XSS payload
4. Open the uploaded SVG image and observe XSS popup

An example SVG `svg-xss-xml.svg` file would be:

````
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <script type="text/javascript">
    alert('XSS-Vulnerability-SVG');
  </script>
</svg>
````

After uploading and browsing the file, the XSS payload will popup, yielding the string "XSS-Vulnerability-SVG".

![image](https://github.com/makeplane/plane/assets/21357789/6d50c239-aeb9-4116-bddf-d758985ba5e9)

![image](https://github.com/makeplane/plane/assets/21357789/203034b9-d30f-43dd-86ae-0140ab2affb8)

Either properly sanitize and restrict file uploads or allow attachment downloads only (no rendering in browsers itself).

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by l4rm4nd** [comment]
Also ensure to set cookie flags like `SameSite` and `HttpOnly`.

https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes

**Comment by githubmilind** [comment]
Is this issue still open? anyone working on it?

**Comment by l4rm4nd** [comment]
> Is this issue still open? anyone working on it?

I've never heard back. Would assume this is still an issue.

**Comment by sheggamharshith** [comment]
hey @l4rm4nd 

Following scenarios are analyzed

- User open the file directly from plaid ( **No impact** no header/cookies are passed verified the same) 
- User open the chat session where svg are rendered ( **No Impact** since  Isomorphic-DomPurify  was used)
- user download and uploaded this file in different medium ( **No Impact** Which is not our concern) 

One more thing you can analyze common pattern that is used  by  well know site such  as slack will allow file with xss vulnerabilities Slack do have XSS reported in 2019. They have mitigated in 2 ways  
    - Files uploaded will not have preview and directly downloaded. 
    - They do provide a direct  preview when they share file to public but with safe preview. 

hey @vamsi  The simple fix for now would be ability for attachment to directly download rather than preview on s3. 

On a serious note the s3 bucket is a private bucket.

**Comment by vihar** [comment]
We’ve moved our S3 storage to private. Please refer to #4181. Additionally, we’ve resolved the direct download issue without redirecting to S3. Please upgrade to our latest version, and if you’re still facing issues, let us know here. Thank you for your patience.
