### ISSUE TITLE
[bug]: 🔥 URGENT: Content Fails to Load Between Subtopics (See Video) 🔥

### ISSUE THREAD

**Issue by yasin172** [makeplane/plane#2580]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

Hello Plane.so team,

First of all, thank you for creating such a wonderful product. I've encountered an issue while using Plane.so and wanted to share it with you. To better explain the issue, I've also recorded a video.

The Issue:
**When I try to navigate between subtopics, the left side of the page and the header load correctly, but the main content does not load.**

### Steps to reproduce

**Steps to Reproduce:**

https://github.com/makeplane/plane/assets/81102121/d8bd6a02-b571-4ca4-ba35-296b6fa8eb23

- Open the main topic.
- Click on the first subtopic and observe the content.
- Click on the second subtopic.
- Observe that the content does not load.

**Additional Information:**

- Browser: (e.g., Google Chrome Version 90)
- Operating System: (e.g., MacOS Catalina)

I wonder if you have any insights into the issue. I am also open to contributing as much as I can.

Thanks and best regards,
[Yasin Atalay]

### Browser

Google Chrome

### Version

Self-hosted

**Comment by vihar** [comment]
@Palanikannan1437, can you debug this one?

**Comment by Palanikannan1437** [comment]
Sure thing @vihar

**Comment by Palanikannan1437** [comment]
Hey @yasin172, this has been fixed in our latest release. Please upgrade to the latest version v0.14-dev by using our [v0.13.x-dev to v0.14.x-dev migration guide](https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x) to see the fix in action!!

Here's a quick demo for the same with the correct behaviour,

https://github.com/makeplane/plane/assets/73993394/141ca3a3-ac70-45cc-bb46-d7f0b668aa55

And in case you're interested, here's the [PR](https://github.com/makeplane/plane/pull/2996) that resolved this!
