### ISSUE TITLE
[bug]: Module not displayed in Gantt chart if it doesn't contain both start and end date

### ISSUE THREAD

**Issue by gegutierrezneri** [makeplane/plane#3052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create modules, I expect to see them in the gantt chart, even if they are not "correct".
If they don't have a start and end date, then they should be visibly obvious that they have an invalid date, and need to be scheduled ASAP.

For an idea on how it could look like, I have some samples from Jira's timeline screen. It uses blurred edges to visibly show that the Module start/end date isn't scheduled yet. 

![Screenshot 2023-12-09 100515](https://github.com/makeplane/plane/assets/31386552/a8c88204-2805-4076-b53a-94e7e2aa7277)

By default, the visible duration along the time axis of such a Module of invalid dates is 1 month.

### Steps to reproduce

1. Create a module
2. Don't add start or end date to it
3. Navigate to Gantt view
4. New Module is currently not visible

### Browser

Mozilla Firefox

### Version

Cloud

**Comment by vihar** [comment]
@gegutierrezneri, thanks for brainstorming with us on this. please note that our gantt chart is still in the development phase, and we are actively working on improving the UX.

regarding the issue of rendering modules or issues on a Gantt without due-date, we're still figuring out, and i like the idea of blurring the edges, and giving the option to user to drag them to set the due-date? what other options would you like to see here, some ideas include:

- distinct color coding
- icons or symbols
- tooltip Information
- customizable labels

if you have any additional ideas or suggestions that you would like to share with us, please feel free to include them. we'll shortly work on the designs and share it here.

**Comment by egutierrez-ar** [comment]
My suggestions would follow closely to Jira's current design language:
See my other improvement suggested: https://github.com/makeplane/plane/issues/3051 


- Color coding on the gantt follows the color coding of the issue's Epic (Module)
  - By color coding modules, users can encode some abstract context of "blues with blues, reds with reds" when having multiple Modules of similar color
- Icons and symbols are only used for displaying abnormalities or inconsistencies in the .
  - Is your issue open and already past its delivery date -> Warning
  - Is your issue scheduled on a cycle outside of the end date? -> Warning on the issue
  - Does your Module have issues scheduled on cycles outside of the start/end date window of the Module? -> Warning on the module
- Tooltip info I would avoid for now due to how busy such a view might already be. Allow for a dialog window to modify the selected issue/cycle/module
- Visible labels would be really convenient along the right sidebar as little pills, along the issue/module of every row in the Gantt.
  - I personally wouldn't display labels, unless the Gantt would allow me to easily filter the labels.
  - Most likely I would make it toggleable as the visuals might get too crowded.

**Comment by gegutierrezneri** [comment]
My suggestions would follow closely to Jira's current design language:
See my other improvement suggested: #3051

    Color coding on the gantt follows the color coding of the issue's Epic (Module)
        By color coding modules, users can encode some abstract context of "blues with blues, reds with reds" when having multiple Modules of similar color
    Icons and symbols are only used for displaying abnormalities or inconsistencies in the plan.
        Is your issue open and already past its delivery date -> Warning
        Is your issue scheduled on a cycle outside of the end date? -> Warning on the issue
        Does your Module have issues scheduled on cycles outside of the start/end date window of the Module? -> Warning on the module
    Tooltip info I would avoid for now due to how busy such a view might already be. Allow for a dialog window to modify the selected issue/cycle/module
    Visible labels would be really convenient along the right sidebar as little pills, along the issue/module of every row in the Gantt.
        I personally wouldn't display labels, unless the Gantt would allow me to easily filter the labels.
        Most likely I would make it toggleable as the visuals might get too crowded.

**Comment by Kritikkkaaa** [comment]
@Shivangi-jain33

**Comment by Kritikkkaaa** [comment]
@Shivangi-jain33

**Comment by Kritikkkaaa** [comment]
@shivangiijain
