### ISSUE TITLE
[bug]:  Can't create cycle which starts in 2023 and ends in 2024

### ISSUE THREAD

**Issue by KarloDerEchte** [makeplane/plane#3200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/41088744/e53d6d91-7686-461e-aa8c-a200195ae216)

If I set the end date to a date which is now in 2024, I get this error that you see in the upper right corner.

### Steps to reproduce

1. Create a Project
2. Make a new Cycle
3. Set start date to like 20th Dezember 2023
4. Set end date to like 6th Januar 2024
5. Try to create the cycle and get the error.

Tested with our current Prod version 0.13.3 and with the latest one 0.14.1

### Browser

Google Chrome

### Version

Self-hosted

**Comment by prateekshourya29** [comment]
Hi @KarloDerEchte,

We checked this issue and it seems that everything is working as expected. This error occurred because there's already an active cycle for the same time period. Plane doesn't allow multiple active cycles, as mentioned in the error message. Please make sure there are no ongoing cycles before creating a new one. If you need further help, let us know.

Thanks,
Prateek Shourya

**Comment by KarloDerEchte** [comment]
@prateekshourya29 Thanks for the information, we have been wondering because the new Cycle has longer period then the current active one.
