### ISSUE TITLE
[bug]: 404 https://xx.com/api/licenses/instances/

### ISSUE THREAD

**Issue by wurst44** [makeplane/plane#3240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, when I do the setup.sh installation for docker self hosted, the app only shows a loading icon.

Any ideas?

### Steps to reproduce

I set the WEB_URL to my domain. I am using my own nginx proxy with letsencrypt so I disabled the integrated one.

The dev console shows https://xx.com/api/licenses/instances/ 404

![image](https://github.com/makeplane/plane/assets/2656697/6081cbbb-e531-4d4d-b249-5ac2e3ffa9bc)

![image](https://github.com/makeplane/plane/assets/2656697/c1214e8b-dfec-47d4-bb6c-a84f820a849f)

![image](https://github.com/makeplane/plane/assets/2656697/5bf12824-a97b-4e04-aad4-242fd8d11956)

![image](https://github.com/makeplane/plane/assets/2656697/3065318d-bb86-4f7c-9889-1b8d81c26967)

### Browser

Google Chrome

### Version

Self-hosted

**Comment by geek-repo** [comment]
+1 same issue

**Comment by halil-bugol** [comment]
@wurst44 Which dockerfile do you deploy containers with?

**Comment by wurst44** [comment]
'curl -fsSL -o setup.sh https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh'
which becomes this one: 
'https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/docker-compose.yml'

**Comment by halil-bugol** [comment]
https://github.com/makeplane/plane/blob/preview/setup.sh Can you try with this sh instead of install.sh? It looks like you're making a mistake during the installation process.

**Comment by wurst44** [comment]
ok, the issue was this comment in the `docker-compose.yml`:
> # Comment this if you already have a reverse proxy running
Which I did at first. Then I uncommented this nginx  (readded the plane nginx) and added it to my (main) Letsencrpyt reverse proxy configuration.

**Comment by kiddhustle** [comment]
> ok, the issue was this comment in the `docker-compose.yml`:
> 
> ```
> # Comment this if you already have a reverse proxy running
>   proxy:
>     container_name: proxy
>     build:
>       context: ./nginx
> [...]
> ```
> 
> Which I did at first and let my Letsencrypt main proxy point to `container_name: web`, that gives me the above 404. Then I uncommented this nginx (readded the plane nginx) and added that one to my (main) Letsencrpyt reverse proxy configuration.

@wurst44 sorry I don't quite follow what action you took to solve the problem.

You said you re-added the plan nginx plan NGINX container, and added this to the LetEncrypt config.

Can you provide an example of your LetsEncrypt config

**Comment by dmascord** [comment]
This was an issue for me too.  If we just use the web container to direct the external HTTP proxy to (such as Traefik), the https://hostname/api calls do not get routed to the api container, and therefore it creates a 404 and hence Plane thinks it is down.
If we go via the proxy container, it obviously maps to the web and the api container, and handles it correctly.
Also, the setup.sh creates a plane.env file, but the docker compose doesn't even read it by default, so had to rename plane.env to .env so that the proxy configuration variables would be read, and proxy would start.

`<Traefik listens on IP>:443 -> <plane-proxy-container>:80 -> <web or api on port>:3000 works.`
