### ISSUE TITLE
[bug]: Changes to Issue State require a Page Refresh to Update

### ISSUE THREAD

**Issue by zackaboyd** [makeplane/plane#3609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After updating to 15.0, When viewing issues for a project, a change made to issue state by another user requires a page refresh to update. This was not the case in previous versions.

### Steps to reproduce

1. Have Issues Open
2. Have another user change a state of an issue
3. Issue does not update onscreen until there is a page refresh

### Browser

Google Chrome

### Version

Cloud

**Comment by marcungeschikts** [comment]
☝🏻 I reproduce this issue, but not only with State, with all the properties update

**Comment by olivierlambert** [comment]
+1 here

**Comment by Arnaldino** [comment]
@pablohashescobar @vamsi Hello, hope you guys are well.
First and foremost, thank you for your amazing work, I just happen to discover Plane and it's awesome.

To illustrate the above issue, I made a short 5 min video:
https://media.agentless.io/PlaneSoFrontEndRefreshIssue.mp4

This does not only affect the cloud but also self hosted versions (tested in both in the video).

Issue: Whenever a user updates any property, creating a new issue or project or changing an issue status, all users need to constantly refresh pages to see the actual change reflected the frontend.

As detailed above it seems this happens since v. 0.15.0. I can't comment here because I onboarded since 0.16.0 which has the seem issue.

The problem also occurs when doing this manually or using the API as you can see in the video. All changes are created an saved in the backend, but the frontend always needs to be refreshed to see those changes in the frontend.

So currently, this prevents seamless collaboration between workspace users and forces them to refresh all pages to view the new changes. This is in my opinion a crucial issue at the moment: users of a workspace should be able to see changes in real time in the UI.

Test setup:
- Cloud & Self Host versions
- Plane Version 0.16.0 latest
- Tested with the same user in 2 different browser sessions.
- Tested with multiple users too, same issue.

**Comment by srinivaspendem** [comment]
Hello @Arnaldino thanks for pitching in here, we do understand the importance having the ability to sync items realtime but haven't prioritised this yet. We are hoping to get to by end of next quarter if possible.

**Comment by olivierlambert** [comment]
Hi @srinivaspendem 

Just to check if I understand correctly: have you fixed the issue? ("closed this a completed") or just closing as "won't fix"?

**Comment by srinivaspendem** [comment]
It's part of our roadmap, and we're actively working on it. We anticipate completion by the end of next quarter.

**Comment by olivierlambert** [comment]
Thank you very much for the news!
