### ISSUE TITLE
[feature]: Project Status & projects view

### ISSUE THREAD

**Issue by Haelle** [makeplane/plane#3875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would be nice to have project status like issues.

Another feature linked is to view projects as a list, and sort and filter them

### Why should this be worked on?

A project can be in the Backlog, in Progress or Done. All of them are importants : 
- backlog : projects being prepared / planned but not in progress
- In Progress : actives projects
- Done : hide finished projects in order not to pollute running projects but keeping infos in Plane

**Comment by srinivaspendem** [comment]
Hello, we currently don't have a way to close the project, but now you should be able to archive any project from the general setting section of the project. Regarding statuses for a project, we will discuss internally and come back.

**Comment by Haelle** [comment]
It's really linked to the project view, being able to have a big picture. Projects should be sortable, and filtered by :
- name
- status 
- start/end date

Currently I put these infos in the name and use the filter/search feature

**Comment by vihar** [comment]
@Haelle, thanks for raising this feature request. Project grouping will be part of our Pro plan and will be available on both cloud and self-hosted versions. I’m sharing some designs we’ve worked on.

![Projects](https://github.com/user-attachments/assets/6cdcad97-9ed1-4ecb-b7f2-341643eb1fb1)

Closing this issue here, as we are taking all conversations related to pro plan on our [Discord](https://discord.com/invite/A92xrEGCge).
