### ISSUE TITLE
[feature]: Notifications, especially email to notify an upcoming due date for issue completion

### ISSUE THREAD

**Issue by RiyaMathew-11** [makeplane/plane#3896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Enable email notifications by choice to be reminded of upcoming due date of an issue completion.

### Why should this be worked on?

We tend to miss deadlines a lot when we work on different projects across the org, and since a small team, we have the scope of not being aware of particular deadlines when we work across projects. 

A quick reminder - say a day before would be very much helpful.😊

**Comment by RiyaMathew-11** [comment]
Hey folks,

Any update on this issue ? - @pushya22 @srinivaspendem

**Comment by pushya22** [comment]
Hi Riya, Thank you for your suggestion. While this feature is indeed on our roadmap, it's not currently among our top priorities. Rest assured, we'll update you as soon as it's ready for release.

**Comment by jlar0che** [comment]
I've just stood up Plane to give it a real-world test drive and have been quite confused regarding notifications. I assumed I would be notified if a Work Item became past due, but nothing ... Looked through the notification setup options and there isn't anything that clearly covers this. This, along with that the OP asked for, feels like extremely basic functionality.

Any updates on more granularity with notifications (since it has been about a year since OPs request)?
