### ISSUE TITLE
[Question] Confusing "Free Plan" and "Upgrade" button for self-hosted deployment

### ISSUE THREAD

**Issue by BorsBorsen** [makeplane/plane#4095]
For Docker self-hosted deployment (followed official documentation) there is a limitation at `https://BASE_URL/WORKSPACE_NAME/active-cycles` page:
![2024-03-29_000310](https://github.com/makeplane/plane/assets/65676842/5f9e5a8a-de7a-4a49-9929-7388007c33a5)

And side menu states "Free Plan"
![2024-03-29_000319](https://github.com/makeplane/plane/assets/65676842/697d6a13-b13d-4a22-a3de-9700ca909e90)

Could you please clarify what are limitations apply to self-hosted version of Plane?

**Comment by genox** [comment]
I would like to know that, too. I appreciate your work and the project being open source and being able to self host it. However, the way it currently looks like implies one is running a "free tier" of a cloud offering on premise that nudges users to switch.

There is no mention on plane.so (I could easily find, anyways) that mentions that the self-hosted version has a different feature set.

I suggest you add a comparison on the pricing page for example or elaborate what the future plan is for this tool in regards to self hosting. Thank you!

**Comment by octavian-regatun** [comment]
Also interested!

**Comment by theparthacus** [comment]
> I would like to know that, too. I appreciate your work and the project being open source and being able to self host it. However, the way it currently looks like implies one is running a "free tier" of a cloud offering on premise that nudges users to switch.
> 
> There is no mention on plane.so (I could easily find, anyways) that mentions that the self-hosted version has a different feature set.
> 
> I suggest you add a comparison on the pricing page for example or elaborate what the future plan is for this tool in regards to self hosting. Thank you!
> 
> 

thank you for pointing this out and the confusion with `Free`. it should be `Community` when you are self-hosting and `Free` on the Cloud. @sriramveeraghanta, let's make this change in the next release.

all plans except [One](https://plane.so/one), irrespective of you being on a self-hosted instance or on the Cloud, will be at parity. for example, Pro, when it launches in a couple months, will be the same for Cloud and self-hosted barring a few self-hosted-specific features for governance and instance security. _those features aren't necessary when you are on the Cloud for obvious reasons_. on both `Free` and `Community` you will see upgrade buttons for paid features that will lead you to relevant upgrade options.

[Plane One](https://plane.so/one) is one such option that's unique to self-hosted instances. while Pro and higher plans will be for larger teams with more advanced features, One is for smaller businesses that would like to get their entire company on Plane for a one-time license.

all paid plans will be governed by a commercial license

**Comment by theparthacus** [comment]
@Haelle

> Also interested for a way to have these features on self hosting (even if it implies to pay)

@octavian-regatun 

> Also interested!

please check out my reply above and [One](https://plane.so/one).

**Comment by TheJMn** [comment]
Hello everyone,
Thanks for your answer. Unfortunately, you should understand that this answer is very sad. Especially since “Free forever” was your motto less than half a year ago.
![image](https://github.com/makeplane/plane/assets/28203541/599b3982-65c3-4de9-a7eb-94ea69936497)

Link: https://github.com/makeplane/plane/issues/2951

**Comment by etaxi341** [comment]
Really sad what OSS Capital L.P. did to this amazing project...

**Comment by genox** [comment]
@theparthacus I understand that you are trying to monetise and there is essentially nothing wrong with that. But you are about to turn into gitlab before you even have a stable product. As a reminder, Jira and gitlab is why we are here in the first place.

**Comment by genox** [comment]
@theparthacus 

> FUP for users on the Cloud does apply and self-hosted Community has a known performance issue beyond 50 users, but that's about it by way of restrictions.

Can you elaborate on that please? Why would you state that 50 users is too much for a self hosted environment without knowing anything about the infrastructure we can provide? How come? Why?

Please, I do not want to sound antagonistic but this is the first time I read this argument. And I say this as part of an org that just bought a Plane One license last week. Note, we bought this license to support an open source project first and foremost. 

To be frank, I don't like where this is going. My OSS/SaaS-rug-pull-after-seed-investment PTSD is in full effect.. ;-)

**Comment by theparthacus** [comment]
@TheJMn

> Hello everyone, Thanks for your answer. Unfortunately, you should understand that this answer is very sad. Especially since “Free forever” was your motto less than half a year ago. From now on it is only free for up to 50 users. ![image]
> 
> Link: #2951

I am not sure where in any response from me you are reading there's an imposed limit of 50 users now. i can understand your confusion about the copy on the site and we will change that, but you are referring to our responses and then you went on to say there are limits. i am confused.

one more time, there are no artificial limits imposed on `Community`. the copy on the site is supposed to be a heads-up for to performance degradation beyond 50 users irrespective of their role. you can continue to run the `Community Edition` up to 100 users or more with increased hardware. there's some performance degradation we are seeing even with increased hardware owed to architecture decisions we took over a year-and-a-half ago, but it's very manageable with increased infra. i hope that's plenty clear.

@etaxi341

> Really sad what OSS Capital L.P. did to this amazing project...

i can answer a specific question you have, but refrain from comments like these, please, without specifying what the _ruining_ is. this isn't in good taste, faith, or acceptable behavior.

i can see you didn't like my response about One or the other plans. are you saying we shouldn't monetize even on features?

@genox

> I understand that you are trying to monetise and there is essentially nothing wrong with that. But you are about to turn into gitlab before you even have a stable product. As a reminder, Jira and gitlab is why we are here in the first place.

okay, I hear you. please tell me how after the clarification i offered above. is it the timing of monetization or the pricing model or something else?

> Can you elaborate on that please? Why would you state that 50 users is too much for a self hosted environment without knowing anything about the infrastructure we can provide? How come? Why?

Please, I do not want to sound antagonistic but this is the first time I read this argument. And I say this as part of an org that just bought a Plane One license last week. Note, we bought this license to support an open source project first and foremost.

To be frank, I don't like where this is going. My OSS/SaaS-rug-pull-after-seed-investment PTSD is in full effect.. ;-)

4 GB RAM, 2vCPU, our standard recommended config for self-hosting Plane, is all i am talking about. there have been several discussions about this on our Discord server, this is and we have taken points to update our Docs to reflect that. give us a little bit here so we can update this there. we only came to know about this after self-hosters reported this. meaning, we didn't know either until recently.

**Comment by genox** [comment]
@theparthacus 

> okay, I hear you. please tell me how after the clarification i offered above. is it the timing of monetization or the pricing model or something else?

Let's circle back to the initial topic this issue is about.

Plane was heavily marketed as an Open Source issue tracker. Github stars, lots of hype. Your market is thirsty for an alternative, we are all tired of Jira and friends and the pricing shenanigans of GitLab in the last 4 years. We (org) were looking for a gitlab replacement for years now and along comes the first solution we actually consider ... and it is open source! Something that is dear to us, something we partake in ourselves.

So we install it and ... it feels like using shareware in the 90s. I don't want to be nudged to upgrade to a Pro plan or buy features  when I use a tool that advertises itself as being OSS and community driven etc. I know the limitations, I installed it and there is probably a reason for me not considering SaaS or Pro or Premium or what have you.

I understand that there will be an monetisation effort, I support it and I really hope you can become a successful business.

But: I would like to ask you to reflect on wether you are an Open Source initiative that monetises with enterprise features or an enterprise solution that uses OSS as some kind of a marketing funnel, for the lack of a better term. They are not the same. And we had a lot of the latter, recently.

I had the same discussion with someone making plugins for an OSS framework recently. I am not sure nudging people into giving you money is "the nice way". It is very aggressive, very on the nose, very hockey stick economics oriented. It is the opposite that we expect when we think about Open Source.

There is plenty of room to monetise, even without an aggressive growth strategy.. alas, you will turn into Atlassian and GitLab. It is the natural way how things go in a capitalistic system unless you consciously try it differently.


In regards to the 50 user thing: this seems to be an unlucky way of presenting that information. I suggest you change the wording.. Right now it looks like an arbitrary imposed limit of some sort. That's how it is written in any other feature comparison card layout, anywhere.

**Comment by theparthacus** [comment]
>So we install it and ... it feels like using shareware in the 90s. I don't want to be nudged to upgrade to a Pro plan or buy features when I use a tool that advertises itself as being OSS and community driven etc. I know the limitations, I installed it and there is probably a reason for me not considering SaaS or Pro or Premium or what have you.

okay, you did that. so we shouldn't show you features that you may find useful in the future if not now, that you may be interested in, that you may want to upgrade for? that sounds counterintuitive to all comms principles that are battle-tested, liked, and loved. in fact, our users complain we don't do enough feature marketing inside and outside the product.

so, yes, we will tell you what existing features do but we will also tell you what paid features you can access if you are interested, at least until a bunch of the community says they don't want to even see a screen like that. we aren't e-mailing folks, we aren't showing pesky banners, we aren't imposing limits on essential features, and we aren't nickle-and-diming with you for those features either. you click a feature that's tagged `Beta` or `Pro`, you see a message to upgrade. think out to half-a-year down the lane. one of your users wants a report, but they can't see it inside the product. they don't know if Plane has it. they have to come to the site or Docs or our blog to figure out about it. now consider the alternative. "Hey, this report exists, but it's paid. Oh, okay. Do we have the budget to upgrade?" that isn't _evil_. it is comms. even the noblest COSS companies do it because the _mission_ is _noble_. 

> I would like to ask you to reflect on wether you are an Open Source initiative that monetises with enterprise features or an enterprise solution that uses OSS as some kind of a marketing funnel, for the lack of a better term. They are not the same. And we had a lot of the latter, recently.

the number of times we have been told that, you would have to take my word for it when I say we have thought about it. our philosophy was and is `open core`. a part of the product will be free on both Cloud and self-hosted. the self-hosted `Community Edition` will be open to contributions either in code or feedback. we will continue to add more features to `Community.` there will e other parts of the product that are paid. where this leads us, I am not wise enough to comment, but each one of our pricing conversations internally ends with, "There will be a Community Edition and people should be able to use it for free to the extent possible by us." stars forbid if the project were to die today, the community could continue to fork it and contribute to it. that, to me, is what open source stands for.

> In regards to the 50 user thing: this seems to be an unlucky way of presenting that information. I suggest you change the wording.. Right now it looks like an arbitrary imposed limit of some sort. That's how it is written in any other feature comparison card layout, anywhere.

yes, absolutely. on it at #4380.

**Comment by genox** [comment]
I just don't want to be nudged. That's all. I don't know why this is so hard to understand.

Your user base is not homogenous and in being tangentially awarded an open source halo, you also attract the difficult user base. Like us. :)

Let the ones that want to get the messages receive them and the allow the ones that prefer visual quietness to find their peace as well. Aka opt-out. Everybody happy. :)

**Comment by genox** [comment]
@theparthacus 

Here's three suggestions you might want to consider:

1. Nudging. This might be actually quite simple to solve. Just don't style those feature buttons or menu items differently. Because that is essentially what is irritating. Keep the splash screen once a feature is clicked. It's as easy as that. Styling variation and highlighting should be reserved for workflow relevant things, not upselling. You are basically begging for some people to become irritated by doing that. Make the community edition visually indistinguishable from premium and you remove all irritation points. Why would you highlight something I cannot use if not to nudge me or remind me that it exists?
2. Open Core vs Open Source. Maybe you could improve in how the project is presented. With everything you wrote above it is pretty clear that this project is not an _Open Source Project_, it is a _SaaS with Open Core_. That might resolve some misunderstandings in the future and people know what they are getting into.

We use GitLab, recently switched to CE after paying for years. However, with as many stabs at GitLab we can make, they never push the limitations in your face and that, to me, is more user friendly than putting icons next to features one can't use to make them stand out even more, you can surely see the irony in that. ;)

**Comment by theparthacus** [comment]
> I just don't want to be nudged. That's all. I don't know why this is so hard to understand.

it's not hard to understand, but i think what i missed clarifying is that we don't just have one kind of user—you—which you point out so well below.

> Your user base is not homogenous and in being tangentially awarded an open source halo, you also attract the difficult user base. Like us. :)

absolutely right. our user base isn't homogenous. _whether you are difficult or not, i leave to you_. to us, all users are the same in their ability and right to give us feedback and ask us to do right by them. what we do, in the end, is let the data guide us. that's all we can stay true to when faced with conflicting choices. i will highlight how below by taking your suggestions as an example.

> Nudging. This might be actually quite simple to solve. Just don't style those feature buttons or menu items differently. Because that is essentially what is irritating. Keep the splash screen once a feature is clicked. It's as easy as that. Styling variation and highlighting should be reserved for workflow relevant things, not upselling. You are basically begging for some people to become irritated by doing that. Make the community edition visually indistinguishable from premium and you remove all irritation points. Why would you highlight something I cannot use if not to nudge me or remind me that it exists?

outside of the fact that this comes across like you know what _all_ users would like, we have, for the record, done that before and had users who, in scathing feedback for how underhanded we were, said, "If it's a paid feature, why aren't you calling it `Paid` or showing something that indicates it is paid?" look at that!

> UX is my pet peeve because I do it all the time.

that users complained shouldn't and isn't surprising, if you take a moment to think about the UX of it. people use software like they are used to. popular software, open source or otherwise, does what we are doing now, what we weren't doing before. we arrived at that by looking at what others were doing and emulating some of that for our screens' real estate. so, what you are calling a nudge—and it could be a nudge how you are describing it—wasn't supposed to be a nudge. our goal should be what you ask us to do, quoted below, but done just right.

> Let the ones that want to get the messages receive them and allow the ones that prefer visual quietness to find their peace as well. Aka opt-out. Everybody happy. :)

right. this will mean some sort of call-out for paid features, but more explicitly. we will talk about it and see if we can't just call those features `Paid`. or something like [this](https://x.com/Jpatton2017/status/1781622591251193931), which is much, much harder.

> Open Core vs Open Source. Maybe you could improve in how the project is presented. With everything you wrote above it is pretty clear that this project is not an Open Source Project, it is a SaaS with Open Core. That might resolve some misunderstandings in the future and people know what they are getting into.

we are pretty popular, so we assumed that the number of times we or someone else has said that, it was clear we we COSS. _COSS is a popular term and stands for everything you are asking us to do._

 1. [recently on Twitter](https://x.com/mfts0/status/1778808324198433013)
 2. [in the run-up to announce One](https://x.com/planepowers/status/1764668162602373500)
 3. [when _heavily_ marketing ourselves as an open-source company](https://x.com/vamsi_kurama/status/1734637301878210766)
 4. [when we announced we raised our seed](https://x.com/scout_flo/status/1726960229814849985)
 5. [during a raging debate about the authenticity of our GitHub stars](https://x.com/areknawo/status/1704092153113100598)
 6. [mentioned by Gergely Orosz](https://x.com/GergelyOrosz/status/1704079330836410480)
 7. [In a letter on the site](https://plane.so/one/why-plane-one)
 8. On our Discord a few times

we will have to figure out how to make this clearer without putting a banner on the site.

> just to be clear, we already did the buy-in

i wanted to thank you for that before, but i also wanted to wait for the end of this debate. thank you for reiterating that, the support this early, and the vote of confidence. we will do our very best not to let you and others down.

> so this is more about principles than anything else.

in sticking to your guns, you have offered me, to the best of my memory, the most interesting, polite debate i have had in my time working with Plane. thank you.

> we take the opportunity to voice both our praise and concerns

don't stop with either. 😉

**Comment by theparthacus** [comment]
#4380 is now done and closed, you guys. ↓ will ship next week to all self-hosted instances.

![Community Edition label on Community release • Plane](https://github.com/makeplane/plane/assets/108609845/7564ffe9-99b5-44ba-a437-df3a162b26c5)
