### ISSUE TITLE
[bug]: state column is broken due to my previous feature request

### ISSUE THREAD

**Issue by JS00001** [makeplane/plane#4924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/49812749/07f51cd5-711a-41f9-862d-2a392db49826)
See the column of 'state'
This is almost certainly an issue with this 'temporary fix' to one of my feature requests.
https://github.com/makeplane/plane/issues/4809#event-13159703656

### Steps to reproduce

Add state column, remove other excess columns.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Version: Latest

**Comment by prateekshourya29** [comment]
Hi @JS00001, Thank you for raising this issue. We identified that the problem was due to the max width constraint applied to the state column, which wasn't considered when other properties are hidden. We've adjusted the CSS logic to ensure the state column expands appropriately when it is the only visible column. The PR #4943 should resolve the unusual white space problem. Please let us know if you encounter any further issues.
