### ISSUE TITLE
[bug]: Pressing return in a rich text field should not submit the field

### ISSUE THREAD

**Issue by jasonvanhattum** [makeplane/plane#5203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I press return / enter in a _rich text_ field I expect my cursor to move to a new line so I can continue editing. Instead, Plane interprets it as a _submit_ action. This is particularly frustrating for bulleted lists.

I appreciate that I can do this with Shift+Enter but many of our users are unaware of this shortcut. I also appreciate that this behaviour is useful in other contexts like creating multiple cards quickly, so I wonder if there should be a distinction between plain text fields where this behaviour is desirable and rich text fields where this behaviour isn't desirable.

### Steps to reproduce

Video of this in practice:

https://github.com/user-attachments/assets/86a78ee8-76f7-45f0-8214-0cf5774ca917

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.22.0

**Comment by pushya22** [comment]
Hi @jasonvanhattum, We appreciate you bringing this to our attention. While this is the current intended behaviour of the product, we value your suggestion. We'll consider it carefully and explore potential heuristic approaches to address the issue in future updates. Thank you for helping us improve.

**Comment by vihar** [comment]
Hi @jasonvanhattum, thank you for this detailed feedback. The current Enter behavior is actually an intentional design choice to maintain consistency across the application - it helps users quickly create and submit content whether they're adding cards, comments, or descriptions.

While `Shift+Enter` for new lines may not be immediately obvious to all users, we've found this pattern is increasingly common in modern applications (like Slack, Discord, etc.) and helps prevent accidental submissions of incomplete content. This consistency in behavior has been valuable for most of our users' workflows.
