### ISSUE TITLE
[bug]: Project member can't add view to favorites

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The star icon promptly changes to yellow but then becomes white again.

Happens with the views Alice created herself and public views alike.

### Steps to reproduce

1. Alice is a Viewer in a workspace and a Member in a project.
2. Alice created a view for herself in the project.
3. Alice wants to favorite the view and clicks on the start icon next to it.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by pushya22** [comment]
Hi @moigagoo This issue is occurring because the user has a viewer role at the workspace level which supersedes the project level permissions , which is currently the intended behaviour of the platform. We are in the process of streamlining all roles across the entire application, which should handle these kind of scenarios.

**Comment by pushya22** [comment]
HI @gchanchal we have streamlined the roles accross platform, you should not be seeing this issue anymore. Feel free to reach out in case of further queries
