### ISSUE TITLE
[feature]: Revert/Convert Issue Types in Pro

### ISSUE THREAD

**Issue by sabgaby** [makeplane/plane#5491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. When issue types are enabled, there is an icon always displayed next to the issue, but when the feature is disabled the icon remains.
![CleanShot 2024-09-02 at 11 00 44@2x](https://github.com/user-attachments/assets/0b1f2b31-24fa-43a5-9836-d7c63917c8db)
2. When issue types are enabled, there is no way to convert or revert existing issues

### Why should this be worked on?

1.1 The icon and color are very distracting, and unnecessary if the feature was accidentally turned on, or is no longer needed. 
1.2 Ability to change the color of the default issue, or have the coloring reversed, i.e. background no color, icon colored.
2. The feature is not useful if you are already in the middle of a project with many issues, or you accidentally created an issue in the wrong type.

**Comment by vihar** [comment]
@sabgaby, thanks for the feedback! A fix is on its way. We are adding the option to update the color and icon for the default issue type.

Enabling issue types is currently an irreversible action, as it requires significant database migrations. The same alert will be shown when enabling it for the first time.

**Comment by sabgaby** [comment]
Ok. But let's say, I enabled it, didn't create new issue types, so its the only one. Can't you then just disable the issues icon? I just find it a bit cluttered. If I could disable the icon for normal issues, even if the project has several issue types, I would probably go for that.

**Comment by vihar** [comment]
@sabgaby, last week we added an update to change the color and icon for the default issue type. We will shortly push changes to enable or disable the issue type icon in the display properties.

![CleanShot 2024-09-09 at 22 26 39@2x](https://github.com/user-attachments/assets/6ccdaaff-3283-41a8-afaf-4e87ea0f335a)

**Comment by vihar** [comment]
@sabgaby, you can now toggle the Issue Type icon and Issue ID from the display properties to remove distractions. While this is a quick fix, we will soon be working on completely reverting Issue Types on Projects. Since this is migration-heavy and could potentially lead to data loss, we’ll be sharing a detailed PRD shortly, explaining how we plan to solve this. In the meantime, we appreciate any feedback. Thank you for your patience.


![CleanShot 2024-10-14 at 07 10 03@2x](https://github.com/user-attachments/assets/118e4eec-a758-4f9e-a733-335a5296a21b)
