### ISSUE TITLE
[feature]: Add Helm Chart for deploying on k8

### ISSUE THREAD

**Issue by PaleHazy** [makeplane/plane#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A Helm chart for quick and painless deployment on Kubernetes

### Why should this be worked on?

- easy installation in a cloud native environment.

**Comment by gcarrarom** [comment]
Big issue here is related to #884

I will share my work in progress tomorrow as an example of what could be used.

**Comment by gcarrarom** [comment]
Here's where I'm at right now: https://github.com/fancy-whale/fancy-charts/tree/main/charts/plane

**Comment by Chris-Greaves** [comment]
I have been trying to get this running with your Helm chart for a few weeks and I've got it deployed and working with my custom domain (although that did take some code changes). My problem at the moment is I get logged out seconds after logging in. I can't even get through the Onboarding steps before it gets 401s and kicks me back to the login. 

I've tried setting the default locale to London (where I am) to see if it was a timezone issue, but that hasn't worked.

I think I'm at a point of abandoning trying to get this self-hosted because there are just too many bugs.

**Comment by shanduur** [comment]
Any updates on this?

**Comment by Kelsinga** [comment]
There is also this one
https://artifacthub.io/packages/helm/makeplane/plane-ce

**Comment by vihar** [comment]
Apologies for the delay, everyone. Plane now officially supports installation using Helm. You can find the documentation here: [link](https://docs.plane.so/self-hosting/kubernetes). Please don't hesitate to reach out if you encounter any issues.
